import { useState, createRef } from 'react'
import Head from 'next/head'
import ReCAPTCHA from "react-google-recaptcha";

export default function Home() {
  const recaptchaRef = createRef();
  const [emailError, setEmailError] = useState('')
  const [email, setEmail] = useState('')
  const [captchaError, setCaptchaError] = useState(false);
  const [successStatus, setSuccessStatus] = useState(false);

  const validateEmail = (email) => {
    return String(email)
      .toLowerCase()
      .match(
        /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
      );
  };

  const onChangeEmail = (e) => {
    const {value} = e.target
    setEmail(value)
  }

  const submitData = (data) => {
    fetch('https://eoql7b7hs2.execute-api.us-east-2.amazonaws.com/dev/v1/early-access', {
      method: 'POST',
      body: JSON.stringify({
        email,
      }),
      headers: {
        'Content-type': 'application/json; charset=UTF-8',
      },
    })
      .then((response) => response.json())
      .then(() => setSuccessStatus(true))
      .finally(() => setSuccessStatus(false));
  }


  const onSubmit = (e) => {
    e.preventDefault();
    debugger;
    const recaptchaValue = recaptchaRef.current.getValue();
    if (!validateEmail(email)) {
      setEmailError('Enter valid Email!')
    } else if (!recaptchaValue) {
      setCaptchaError(true)
    } else {
      setCaptchaError(false)
      setEmailError(null)
      submitData(email) 
    }
  }

  const secretKey = "6LctN-cfAAAAABG5jg9iToRqj-IojqOhY5hBltWS"

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center flex-col">
        <div
          className="max-w-sm w-full"
        >
          <img src="/Full Logo V2@4x.png" className="w-100 h-auto" alt="logo"/>
        </div>
        <p className="text-2xl my-12">
          The Credit market for<br/>
          cryptocurrency investors
        </p>
        <form className="my-3" onSubmit={onSubmit}>
          <div className='my-3'>
            <input
              type="text"
              className="p-2 border-4 border-[#29564B] outline-none text-lg"
              onChange={onChangeEmail}
              value={email}
              placeholder="Enter Your Email"
            />
            <div className='text-red-500'>
              {emailError}
            </div>
          </div>
          <div className='my-3'>
            <ReCAPTCHA
              ref={recaptchaRef}
              sitekey="6LctN-cfAAAAAPoMPQhN4xmcxvQ9GmO2gEKzPJqQ"
              onChange={() => captchaError(false)}
            />
          </div>
          <button className="p-3 text-lg flex-shrink-0 text-white bg-[#29564B]" type="submit">
            Contact us
          </button>
        </form>
      </main>
    </div>
  )
}
